### ISSUE TITLE
Please add hide page count ?

### ISSUE THREAD

**Issue by eArabic** [DarkoBorojevic/PHP-PDO-pagination#1]
Hello
Thank you very much for this script.
Please add hide page count if too many pages.
Attachment picture shows that, sorry I have weak English.
![35781234-79784262-09f8-11e8-9155-81e1bf7ad198](https://user-images.githubusercontent.com/24383546/36661393-33663e14-1aec-11e8-9168-6a3272e4a0b8.png)

![4](https://user-images.githubusercontent.com/24383546/36661450-5414ed9a-1aec-11e8-886c-80fb9a51153e.png)

**Comment by DarkoBorojevic** [comment]
Will do. Thank you for your comment
